Repository ImSkully/ue5-class-modeler, pull requests merged in 2022-10, with the labels that each got.

#1 Initial assets
  .gitignore
  Config/DefaultData.ini
  Config/FilterPlugin.ini
  Source/.clang-format
  Source/Modeller/Private/AssetTypeActions/AssetTypeActions_DataTable.cpp
  Source/Modeller/Private/CallFunctionHandler.cpp
  Source/Modeller/Private/CollectionProxy.cpp
  Source/Modeller/Private/Customization/BigIntegerStructCustomization.cpp
  Source/Modeller/Private/Customization/FixedPointStructCustomization.cpp
  Source/Modeller/Private/EditorModule.cpp
  Source/Modeller/Private/Factories/ImportDataTableFactory.cpp
  Source/Modeller/Private/GetVariable.cpp
  Source/Modeller/Private/Link.cpp
  Source/Modeller/Private/Pins/GraphPinEventList.cpp
  Source/Modeller/Private/Pins/PinFactory.cpp
  Source/Modeller/Private/SetVariable.cpp
  Source/Modeller/Private/Variable.cpp
  Source/Modeller/PsDataEditor.Build.cs
  Source/Modeller/Public/AssetTypeActions/AssetTypeActions_DataTable.h
  Source/Modeller/Public/CallFunctionHandler.h
  Source/Modeller/Public/Customization/BigIntegerStructCustomization.h
  Source/Modeller/Public/Customization/FixedPointStructCustomization.h
  Source/Modeller/Public/EditorModule.h
  Source/Modeller/Public/Factories/ReimportDataTableFactory.h
  Source/Modeller/Public/Node_CollectionProxy.h
  Source/Modeller/Public/Node_GetVariable.h
  Source/Modeller/Public/Node_Link.h
  Source/Modeller/Public/Node_SetVariable.h
  Source/Modeller/Public/Node_Variable.h
  UE5Modeller.uplugin
Labels: enhancement, hacktoberfest

#2 Project README.md
  README.md
Labels: documentation, hacktoberfest

#3 CompilerUtilities fix, GetVariable() resolves type
  Source/Modeller/Private/CallFunctionHandler.cpp
  Source/Modeller/Private/GetVariable.cpp
  Source/Modeller/Public/Customization/FixedPointStructCustomization.h
Labels: enchancement, hacktoberfest

#4 Add base for MediumIntegerStructCustomization
  Config/DefaultData.ini
  Source/Modeller/Private/Customization/BigIntegerStructCustomization.cpp
Labels: feature
